# Generated by Selenium IDE (Updated)

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options


class TestSmoketest():

    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        options.add_argument("--window-size=1920,1080")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_smoketest(self):
        # Navigate to home page
        self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")

        # Verify logo exists
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
        assert len(elements) > 0

        # Verify headings
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"

        # Verify page title
        assert self.driver.title == "Teton Idaho CoC"

        # Click Join Us link
        self.driver.find_element(By.LINK_TEXT, "Join Us").click()

        # Wait for join form to load
        WebDriverWait(self.driver, 5).until(
            EC.presence_of_element_located((By.NAME, "fname"))
        )

        # Verify First Name field exists
        assert len(self.driver.find_elements(By.NAME, "fname")) > 0

        # Fill out first page
        self.driver.find_element(By.NAME, "fname").send_keys("John")
        self.driver.find_element(By.NAME, "lname").send_keys("Doe")
        self.driver.find_element(By.NAME, "bizname").send_keys("JD Services")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Owner")

        # Click Next Step
        self.driver.find_element(By.NAME, "submit").click()

        # Wait for email field on step 2
        WebDriverWait(self.driver, 5).until(
            EC.presence_of_element_located((By.NAME, "email"))
        )

        # Verify Email field exists
        assert len(self.driver.find_elements(By.NAME, "email")) > 0
